

services:
  db:
    image: postgres:14.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn cms.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
  celery:
    restart: always
    build:
      context: .
    command: celery -A cms worker -l INFO
    depends_on:
      - db
      - redis
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume:
#version: '3.8'
#
#services:
#  db:
#    image: postgres:14.5-alpine
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    env_file:
#      - ./.env.prod.db
#  web:
#    build:
#      context: ./
#      dockerfile: Dockerfile.prod
#    command: gunicorn cms.wsgi:application --bind 0.0.0.0:8000
#    expose:
#      - 8000
#    env_file:
#      - ./.env.prod
#    depends_on:
#      - db
#  nginx:
#    build: ./nginx
#    ports:
#      - 1337:80
#    depends_on:
#      - web
#  redis:
#    image: redis:alpine
#    ports:
#      - '6379:6379'
#  celery:
#    restart: always
#    build:
#      context: .
#    command: celery -A cms worker -l INFO
##    volumes:
##      - ./app:/web
#    depends_on:
#      - db
#      - redis
#      - web
#volumes:
#  postgres_data:
