# Generated by Django 4.0.6 on 2022-07-11 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='backgroundbanner/', verbose_name='Фото на фоне')),
                ('type', models.CharField(choices=[('Фото на фоне', 'фото на фоне'), ('Пустой фон', 'Пустой фон')], max_length=32, null=True)),
                ('title', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BannerBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turning_speed', models.CharField(choices=[('3c', 3), ('5c', 5), ('10c', 10)], default='3c', max_length=32)),
                ('turning_on', models.BooleanField(default=True)),
                ('news_or_main', models.CharField(choices=[('news', 'new'), ('main', 'main')], default='main', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название кинотеатра')),
                ('describe', models.TextField(verbose_name='Описание')),
                ('conveniences', models.TextField(blank=True, null=True, verbose_name='Удобства')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='cinema/', verbose_name='Логотип')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='cinema/', verbose_name='Фото верхнего баннера')),
            ],
            options={
                'verbose_name': 'Кинотеатр',
                'verbose_name_plural': 'Кинотеатры',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=32, null=True, verbose_name='Название фильма')),
                ('describe', models.TextField(blank=True, max_length=200, null=True, verbose_name='Описание фильма')),
                ('link_trailer', models.URLField(blank=True, null=True, verbose_name='Ссылка на фильм')),
                ('f2d', models.BooleanField(blank=True, null=True, verbose_name='2D')),
                ('f3d', models.BooleanField(blank=True, null=True, verbose_name='3D')),
                ('IMAX', models.BooleanField(blank=True, null=True, verbose_name='IMAX')),
                ('date_of_premier', models.DateTimeField(blank=True, null=True, verbose_name='Дата премьеры')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='film/', verbose_name='Логотип фильма')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Номер зала')),
                ('hall_describe', models.TextField(blank=True, max_length=200, null=True, verbose_name='Описание зала')),
                ('map', models.ImageField(blank=True, null=True, upload_to='hall/', verbose_name='Карта зала')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='hall/', verbose_name='Холл баннер')),
                ('places', models.JSONField(blank=True, null=True, verbose_name='Места')),
                ('cinema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema', verbose_name='Кинотеатр')),
                ('pictures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.gallery', verbose_name='Картинки')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=32, null=True, verbose_name='Заголовок СЕО')),
                ('keyword', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'СЕО блок',
                'verbose_name_plural': 'СЕО блоки',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Номер сеанса')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата сеанса')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Price')),
                ('film', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.film', verbose_name='Название фильма')),
                ('hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.hall', verbose_name='Номер зала')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.session')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('gallery', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.gallery')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Не указано название страницы', max_length=50, null=True)),
                ('describe', models.TextField(max_length=500, null=True)),
                ('logo', models.ImageField(upload_to='pages/')),
                ('pictures', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.gallery')),
                ('seo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.seo')),
            ],
        ),
        migrations.CreateModel(
            name='NewsOrSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Дата события')),
                ('title', models.CharField(default='Не указан заголовок статьи', max_length=50)),
                ('describe', models.TextField(max_length=500, null=True)),
                ('logo', models.ImageField(upload_to='news_or_sale/')),
                ('link', models.URLField(verbose_name='Ссылка на новость')),
                ('status', models.BooleanField(default=True)),
                ('news_or_sale', models.CharField(choices=[('news', 'new'), ('sale', 'sale')], default='news', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('pictures', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.gallery')),
                ('seo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.seo')),
            ],
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='MainPage', max_length=40)),
                ('phone1', models.CharField(max_length=15)),
                ('phone2', models.CharField(max_length=15)),
                ('seo_text', models.TextField(max_length=500)),
                ('seo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.seo')),
            ],
        ),
        migrations.AddField(
            model_name='hall',
            name='seo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema.seo', verbose_name='СЕО блок'),
        ),
        migrations.AddField(
            model_name='film',
            name='pictures',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.gallery', verbose_name='Картинки'),
        ),
        migrations.AddField(
            model_name='film',
            name='seo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cinema.seo', verbose_name='SEO блок'),
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_name', models.CharField(max_length=40, null=True, verbose_name='Название кинотеатра')),
                ('address', models.CharField(default='Не указан адресс', max_length=50, null=True)),
                ('coordinates', models.URLField(verbose_name='Координаты кинотеатра')),
                ('logo', models.ImageField(null=True, upload_to='contact/')),
                ('seo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.seo')),
            ],
        ),
        migrations.AddField(
            model_name='cinema',
            name='pictures',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.gallery', verbose_name='Галерея картинок'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='seo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema.seo', verbose_name='СЕО блок'),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='banner_box/')),
                ('url', models.URLField(null=True)),
                ('text', models.TextField(max_length=500, null=True)),
                ('banner_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.bannerbox', verbose_name='BannerBox')),
            ],
        ),
    ]
