# Generated by Django 4.0.6 on 2022-07-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
