# Generated by Django 4.0.6 on 2022-07-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_alter_film_imax_alter_film_date_of_premier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsorsale',
            name='link',
            field=models.URLField(null=True, verbose_name='Ссылка на новость'),
        ),
        migrations.AlterField(
            model_name='newsorsale',
            name='logo',
            field=models.ImageField(null=True, upload_to='news_or_sale/'),
        ),
        migrations.AlterField(
            model_name='newsorsale',
            name='news_or_sale',
            field=models.CharField(choices=[('news', 'new'), ('sale', 'sale')], default='news', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='newsorsale',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
