# Generated by Django 4.0.6 on 2022-07-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_alter_newsorsale_link_alter_newsorsale_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsorsale',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='newsorsale',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='news_or_sale/'),
        ),
        migrations.AlterField(
            model_name='newsorsale',
            name='title',
            field=models.CharField(help_text='Название новости', max_length=50),
        ),
    ]
