# Generated by Django 4.0.6 on 2022-07-13 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_alter_newsorsale_date_alter_newsorsale_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='number',
        ),
        migrations.AddField(
            model_name='hall',
            name='date',
            field=models.DateField(default=datetime.date(2022, 7, 13)),
        ),
        migrations.AddField(
            model_name='hall',
            name='title',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='Название зала'),
        ),
    ]
