# Generated by Django 4.0.6 on 2022-07-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0014_alter_hall_date_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='conveniences_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Удобства'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='conveniences_ua',
            field=models.TextField(blank=True, null=True, verbose_name='Удобства'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='describe_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='describe_ua',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='name_ru',
            field=models.CharField(max_length=32, null=True, verbose_name='Название кинотеатра'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='name_ua',
            field=models.CharField(max_length=32, null=True, verbose_name='Название кинотеатра'),
        ),
        migrations.AddField(
            model_name='hall',
            name='hall_describe_ru',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Описание зала'),
        ),
        migrations.AddField(
            model_name='hall',
            name='hall_describe_ua',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Описание зала'),
        ),
        migrations.AddField(
            model_name='hall',
            name='title_ru',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Название зала'),
        ),
        migrations.AddField(
            model_name='hall',
            name='title_ua',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Название зала'),
        ),
        migrations.AddField(
            model_name='newsorsale',
            name='describe_ru',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='newsorsale',
            name='describe_ua',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='newsorsale',
            name='title_ru',
            field=models.CharField(help_text='Название новости', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newsorsale',
            name='title_ua',
            field=models.CharField(help_text='Название новости', max_length=50, null=True),
        ),
    ]
