# Generated by Django 4.0.6 on 2022-07-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0015_cinema_conveniences_ru_cinema_conveniences_ua_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinema',
            old_name='conveniences_ua',
            new_name='conveniences_uk',
        ),
        migrations.RenameField(
            model_name='cinema',
            old_name='describe_ua',
            new_name='describe_uk',
        ),
        migrations.RenameField(
            model_name='cinema',
            old_name='name_ua',
            new_name='name_uk',
        ),
        migrations.RenameField(
            model_name='hall',
            old_name='hall_describe_ua',
            new_name='hall_describe_uk',
        ),
        migrations.RenameField(
            model_name='hall',
            old_name='title_ua',
            new_name='title_uk',
        ),
        migrations.RenameField(
            model_name='newsorsale',
            old_name='describe_ua',
            new_name='describe_uk',
        ),
        migrations.RenameField(
            model_name='newsorsale',
            old_name='title_ua',
            new_name='title_uk',
        ),
        migrations.AddField(
            model_name='pages',
            name='describe_ru',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='describe_uk',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='title_ru',
            field=models.CharField(default='Не указано название страницы', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='title_uk',
            field=models.CharField(default='Не указано название страницы', max_length=50, null=True),
        ),
    ]
