# Generated by Django 4.0.6 on 2022-07-23 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0016_rename_conveniences_ua_cinema_conveniences_uk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='date',
            field=models.DateField(default=datetime.date(2022, 7, 23)),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='date',
            field=models.DateField(default=datetime.date(2022, 7, 23)),
        ),
        migrations.AddField(
            model_name='pages',
            name='date',
            field=models.DateField(default=datetime.date(2022, 7, 23)),
        ),
        migrations.AlterField(
            model_name='hall',
            name='date',
            field=models.DateField(default=datetime.date(2022, 7, 23)),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='title',
            field=models.CharField(default='Главная страница', max_length=40),
        ),
    ]
