# Generated by Django 4.0.6 on 2022-07-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0020_mainpage_status_alter_contacts_date_alter_hall_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
