# Generated by Django 4.0.6 on 2022-07-24 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0021_contacts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='seo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.seo'),
        ),
    ]
