# Generated by Django 4.0.6 on 2022-07-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0023_alter_contacts_date_alter_contacts_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='status',
            field=models.BooleanField(blank=True),
        ),
    ]
