# Generated by Django 4.0.6 on 2022-07-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0026_alter_contacts_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='describe_ru',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Описание фильма'),
        ),
        migrations.AddField(
            model_name='film',
            name='describe_uk',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Описание фильма'),
        ),
        migrations.AddField(
            model_name='film',
            name='title_ru',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Название фильма'),
        ),
        migrations.AddField(
            model_name='film',
            name='title_uk',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Название фильма'),
        ),
    ]
