# Generated by Django 4.0.6 on 2022-07-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0027_film_describe_ru_film_describe_uk_film_title_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='date_of_premier',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата премьеры'),
        ),
    ]
