# Generated by Django 4.0.6 on 2022-07-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0028_alter_film_date_of_premier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerbox',
            name='news_or_main',
        ),
        migrations.AddField(
            model_name='bannerbox',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
