# Generated by Django 4.0.6 on 2022-07-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0029_remove_bannerbox_news_or_main_bannerbox_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerbox',
            name='news_or_main',
            field=models.CharField(choices=[('news', 'new'), ('main', 'main')], default='main', max_length=32),
        ),
        migrations.AlterField(
            model_name='bannerbox',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
