# Generated by Django 4.0.6 on 2022-07-26 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0033_alter_banner_banner_box_alter_contacts_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='photo',
            new_name='image',
        ),
    ]
