# Generated by Django 4.0.6 on 2022-07-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0034_rename_photo_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerbox',
            name='turning_on',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='bannerbox',
            name='turning_speed',
            field=models.CharField(blank=True, choices=[('3c', 3), ('5c', 5), ('10c', 10)], default='3c', max_length=32, null=True),
        ),
    ]
