# Generated by Django 4.0.6 on 2022-07-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0036_alter_bannerbox_news_or_main_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerbox',
            name='news_or_main',
            field=models.CharField(choices=[('news', 'new'), ('main', 'main')], default='main', max_length=32),
        ),
        migrations.AlterField(
            model_name='bannerbox',
            name='turning_speed',
            field=models.CharField(blank=True, choices=[('3c', 3), ('5c', 5), ('10c', 10)], default='3c', max_length=32, null=True),
        ),
    ]
