# Generated by Django 4.0.6 on 2022-07-26 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0038_alter_bannerbox_turning_speed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backgroundbanner',
            old_name='photo',
            new_name='image',
        ),
    ]
