# Generated by Django 4.0.6 on 2022-07-30 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0039_rename_photo_backgroundbanner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='describe',
            field=models.TextField(max_length=1500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='describe_ru',
            field=models.TextField(max_length=1500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='describe_uk',
            field=models.TextField(max_length=1500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='date',
            field=models.DateField(default=datetime.date(2022, 7, 30)),
        ),
        migrations.AlterField(
            model_name='hall',
            name='date',
            field=models.DateField(default=datetime.date(2022, 7, 30)),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='date',
            field=models.DateField(default=datetime.date(2022, 7, 30)),
        ),
        migrations.AlterField(
            model_name='pages',
            name='date',
            field=models.DateField(default=datetime.date(2022, 7, 30)),
        ),
    ]
