# Generated by Django 4.0.6 on 2022-07-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0040_alter_cinema_describe_alter_cinema_describe_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='describe',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='describe_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='describe_uk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
