# Generated by Django 4.0.6 on 2022-08-01 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0041_alter_cinema_describe_alter_cinema_describe_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='date',
            field=models.DateField(default=datetime.date(2022, 8, 1)),
        ),
        migrations.AlterField(
            model_name='hall',
            name='date',
            field=models.DateField(default=datetime.date(2022, 8, 1)),
        ),
        migrations.AlterField(
            model_name='hall',
            name='hall_describe',
            field=models.TextField(blank=True, null=True, verbose_name='Описание зала'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='hall_describe_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание зала'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='hall_describe_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Описание зала'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='date',
            field=models.DateField(default=datetime.date(2022, 8, 1)),
        ),
        migrations.AlterField(
            model_name='pages',
            name='date',
            field=models.DateField(default=datetime.date(2022, 8, 1)),
        ),
    ]
