# Generated by Django 4.0.6 on 2022-08-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0043_alter_session_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerbox',
            name='turning_speed',
            field=models.CharField(choices=[('3', '3c'), ('5', '5c'), ('10', '10c')], default='3c', max_length=32),
        ),
    ]
