# Generated by Django 4.0.6 on 2022-08-02 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0045_alter_bannerbox_turning_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='date',
            field=models.DateField(default=datetime.date(2022, 8, 2)),
        ),
        migrations.AlterField(
            model_name='hall',
            name='date',
            field=models.DateField(default=datetime.date(2022, 8, 2)),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='date',
            field=models.DateField(default=datetime.date(2022, 8, 2)),
        ),
        migrations.AlterField(
            model_name='pages',
            name='date',
            field=models.DateField(default=datetime.date(2022, 8, 2)),
        ),
    ]
