# Generated by Django 4.0.6 on 2022-08-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0047_alter_newsorsale_describe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='coordinates',
            field=models.URLField(max_length=1000, verbose_name='Координаты кинотеатра'),
        ),
    ]
