# Generated by Django 4.0.6 on 2022-08-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0048_alter_contacts_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='address',
            field=models.CharField(default='Не указан адресс', max_length=500, null=True),
        ),
    ]
