# Generated by Django 4.0.6 on 2022-08-03 06:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0049_alter_contacts_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='date',
            field=models.DateField(default=datetime.date(2022, 8, 3)),
        ),
        migrations.AlterField(
            model_name='film',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='film/', verbose_name='Логотип фильма'),
        ),
        migrations.AlterField(
            model_name='film',
            name='seo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cinema.seo', verbose_name='SEO блок'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='date',
            field=models.DateField(default=datetime.date(2022, 8, 3)),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='date',
            field=models.DateField(default=datetime.date(2022, 8, 3)),
        ),
        migrations.AlterField(
            model_name='pages',
            name='date',
            field=models.DateField(default=datetime.date(2022, 8, 3)),
        ),
    ]
