# Generated by Django 4.0.6 on 2022-08-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0050_alter_contacts_date_alter_film_logo_alter_film_seo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Номер сеанса'),
        ),
    ]
