# Generated by Django 4.0.6 on 2022-08-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0051_alter_session_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='html_template/')),
            ],
        ),
    ]
