# Generated by Django 4.0.6 on 2022-08-09 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0052_htmltemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='place',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='date',
            field=models.DateField(default=datetime.date(2022, 8, 9)),
        ),
        migrations.AlterField(
            model_name='hall',
            name='date',
            field=models.DateField(default=datetime.date(2022, 8, 9)),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='date',
            field=models.DateField(default=datetime.date(2022, 8, 9)),
        ),
        migrations.AlterField(
            model_name='pages',
            name='date',
            field=models.DateField(default=datetime.date(2022, 8, 9)),
        ),
    ]
