# Generated by Django 4.0.6 on 2022-08-10 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0053_session_place_alter_contacts_date_alter_hall_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='date',
            field=models.DateField(default=datetime.date(2022, 8, 10)),
        ),
        migrations.AlterField(
            model_name='hall',
            name='date',
            field=models.DateField(default=datetime.date(2022, 8, 10)),
        ),
        migrations.AlterField(
            model_name='hall',
            name='places',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Места'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='date',
            field=models.DateField(default=datetime.date(2022, 8, 10)),
        ),
        migrations.AlterField(
            model_name='pages',
            name='date',
            field=models.DateField(default=datetime.date(2022, 8, 10)),
        ),
        migrations.AlterField(
            model_name='session',
            name='place',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
