# Generated by Django 4.0.6 on 2022-08-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0054_alter_contacts_date_alter_hall_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='places',
            field=models.FileField(blank=True, null=True, upload_to='places/', verbose_name='Места'),
        ),
        migrations.AlterField(
            model_name='session',
            name='place',
            field=models.FileField(blank=True, null=True, upload_to='places/'),
        ),
    ]
