# Generated by Django 4.0.6 on 2022-08-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0055_alter_hall_places_alter_session_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='places',
            field=models.JSONField(blank=True, null=True, verbose_name='Места'),
        ),
        migrations.AlterField(
            model_name='session',
            name='place',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
