# Generated by Django 4.0.6 on 2022-08-15 03:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0061_alter_contacts_date_alter_hall_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmltemplate',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 15, 3, 50, 1, 596626, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 8, 15, 3, 50, 1, 594621, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hall',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 8, 15, 3, 50, 1, 590667, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 8, 15, 3, 50, 1, 594230, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pages',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 8, 15, 3, 50, 1, 595132, tzinfo=utc)),
        ),
    ]
