# Generated by Django 4.0.6 on 2022-08-16 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0062_htmltemplate_date_alter_contacts_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 8, 16, 7, 56, 43, 893089)),
        ),
        migrations.AlterField(
            model_name='hall',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 8, 16, 7, 56, 43, 877406)),
        ),
        migrations.AlterField(
            model_name='htmltemplate',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 16, 7, 56, 43, 900179)),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 8, 16, 7, 56, 43, 891524)),
        ),
        migrations.AlterField(
            model_name='pages',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 8, 16, 7, 56, 43, 894826)),
        ),
    ]
