# Generated by Django 4.0.6 on 2022-08-16 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0063_alter_contacts_date_alter_hall_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 8, 16, 7, 58, 23, 949007)),
        ),
        migrations.AlterField(
            model_name='htmltemplate',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
